### ISSUE TITLE
Distance Buzzer Project

### ISSUE THREAD

**Issue by cppenloglou** [Heron-Robotics/main#2]
# Σχετικά με το project
Μάλλον έγινε κάποιο λάθος σχετικά με το ανέβασμα του project στο repository, δεν πειράζει όλα καλά το έφτιαξα, ουσιαστικά πρέπει να είναι τα project σας μέσα στο φάκελο training 23 -24 και σε ύποφάκελο. *Δεν έσβησα την αρχική δουλεία* **περιμένω** απο σας να το κάνετε αφου δείτε αυτο το issue.
# Επίσης είπαμε Pull Request
Οταν δεν είστε σίγουροι για αυτό που θα ανεβάζετε θα κάνετε ένα νέο branch και απο εκέι Pull request ωστε να το αποδεχθούμε.

**Comment by giorgoskaranikolopoulos** [comment]
Νομίζω το έφτιαξα αδερφέ. Πες μου αν βρεις κάποιο άλλο λάθος.

**Comment by cppenloglou** [comment]
Ωραία το είδα μια χαρά είναι!
Κλείσε τώρα το issue.

**Comment by giorgoskaranikolopoulos** [comment]
Πάνω αριστερά λέει πως είναι ήδη κλειστό.

Στις Τρί 2 Ιαν 2024, 8:11 μ.μ. ο χρήστης Chrysostomos Penloglou <
***@***.***> έγραψε:
